name: 24-Lamb
description: code and thought 
url: http://24hours.github.io
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: [tables]
# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Mulsec

author:
  name: Lee Yeong Khang
  email: sindrosa.24@gmail.com
  github: 24hours
  twitter: sindrosa
  bio: Read, Do, Write, Repeat
  disqus-id: 24sinner

BASE_PATH:
