name: 24-Lamb
description: code and thought 
url: http://24hours.github.io
markdown: redcarpet
redcarpet:
  extensions: [tables]
paginate: 5
highlighter: pygments

rss-feed-limit: 10

disqus-id: 24sinner
twitter: sindrosa
github: 24hours
google: 116936874740701065822

permalink: /:title